In [ ]:
#Theory

#1. Explain the purpose and advantages of NumPy in scientific computing and data analysis. How does it
#enhance Python's capabilities for numerical operations?
NumPy is a powerful library in Python that serves as the foundation for numerical and scientific computing. Its purpose is to provide support for large, multi-dimensional arrays and matrices, as well as a collection of mathematical functions to operate on these arrays efficiently. Here’s an explanation of the advantages and how it enhances Python’s capabilities for numerical operations:

### Purpose of NumPy in Scientific Computing and Data Analysis:
'''1. **Efficient Storage and Processing of Data**:
   - NumPy allows the creation of high-performance arrays (known as `ndarray`), which are more memory efficient and faster than Python's native lists. Arrays can hold large datasets in memory, and NumPy optimizes these arrays for fast computation.

2. **Multi-Dimensional Array Support**:
   - NumPy provides `ndarray`, a flexible object to represent vectors, matrices, and higher-dimensional arrays (tensors). This makes it suitable for scientific computing tasks that require multi-dimensional data structures, such as in physics simulations or machine learning.

3. **Vectorized Operations**:
   - NumPy supports vectorized operations, which means that instead of writing explicit loops for element-wise calculations (like adding two arrays), NumPy allows you to perform the operation directly on arrays. This is not only more concise but also far more efficient in terms of both speed and memory usage.

4. **Linear Algebra and Mathematical Functions**:
   - NumPy provides built-in functions for performing complex mathematical operations, such as matrix multiplication, Fourier transforms, and random number generation. This is essential for scientific tasks in fields such as physics, economics, and machine learning.

5. **Interoperability with Other Libraries**:
   - NumPy is highly compatible with other Python libraries, such as SciPy, Pandas, and scikit-learn, which build upon its functionality. For example, Pandas uses NumPy under the hood for handling data structures like `DataFrame`.

### Advantages of Using NumPy:
1. **Speed**:
   - NumPy is much faster than Python's native lists for numerical operations because it leverages optimized, compiled code. It is built on top of libraries like BLAS (Basic Linear Algebra Subprograms) and LAPACK (Linear Algebra PACKage), which are written in C and Fortran for high performance.

2. **Concise Code**:
   - NumPy allows you to perform complex operations with a single line of code, replacing the need for multiple loops or manual indexing. For example, multiplying two matrices is as simple as `C = A @ B` in NumPy, whereas it would require nested loops in pure Python.

3. **Memory Efficiency**:
   - NumPy arrays consume less memory than Python lists because they store data in contiguous blocks of memory. This improves both speed and memory usage, especially when handling large datasets.

4. **Support for Advanced Mathematical Operations**:
   - NumPy includes a broad range of mathematical operations, including:
     - **Linear Algebra** (dot products, matrix multiplication, eigenvalue decomposition)
     - **Statistics** (mean, median, standard deviation)
     - **Random Number Generation** (random sampling, normal distribution, etc.)
     - **Fourier Transforms** and other signal processing tools.

5. **Easy Integration with Other Tools**:
   - NumPy is widely used as the base array type for scientific tools in Python, making it easy to integrate with libraries like SciPy (for advanced scientific algorithms), scikit-learn (machine learning), Matplotlib (for plotting), and Pandas (for data manipulation).

### How NumPy Enhances Python’s Capabilities for Numerical Operations:
- **Python’s Built-in Limitations**: Python’s built-in lists are flexible but inefficient for numerical operations. For instance, a list of numbers can't easily support operations like matrix multiplication or element-wise arithmetic. Python also lacks efficient storage and processing for large datasets.

- **NumPy’s Solution**:
   - **Efficient Array Structure**: The `ndarray` object in NumPy overcomes this limitation by providing an optimized data structure for large numerical datasets.
   - **Broadcasting**: NumPy can apply operations to arrays of different shapes without needing explicit loops. This feature, known as **broadcasting**, makes it possible to perform arithmetic on arrays of different sizes without resizing them manually, which greatly enhances both speed and flexibility.

   For example:
   ```python
   import numpy as np
   A = np.array([1, 2, 3])
   B = np.array([4, 5, 6])
   result = A + B  # element-wise addition
   ```

   Broadcasting allows operations on arrays with different shapes (e.g., adding a scalar to an array), which is often used in machine learning and scientific computations.

- **Optimized Performance**: NumPy uses highly optimized C and Fortran libraries under the hood, making operations on arrays much faster compared to Python’s built-in list handling. This means complex numerical algorithms that would be too slow with standard Python can be performed efficiently with NumPy.

In summary, NumPy transforms Python into a powerful tool for scientific computing by providing efficient, flexible, and fast array manipulation, as well as a rich set of mathematical functions. It significantly enhances Python's capabilities for numerical analysis, making it a go-to library for anyone working in data science, machine learning, physics, engineering, or other domains that require extensive numerical computing.'''

In [ ]:
#2. Compare and contrast np.mean() and np.average() functions in NumPy. When would you use one over the other?
In NumPy, both `np.mean()` and `np.average()` are used to compute the arithmetic mean (average) of an array, but they have subtle differences in functionality. Here’s a comparison between them:

### `np.mean()`

'''- **Purpose**:
  - Computes the **arithmetic mean** (average) of the elements along a specified axis of an array.
  - The mean is calculated by summing all the elements and then dividing by the number of elements.

- **Signature**:
  ```python
  np.mean(a, axis=None, dtype=None, out=None, keepdims=False)
  ```

- **Parameters**:
  - `a`: The input array.
  - `axis`: The axis along which to compute the mean. Default is `None`, which means it computes the mean of all the elements.
  - `dtype`: The data type to use for the computation. If `None`, it defaults to the data type of the input array.
  - `out`: An alternative output array to store the result.
  - `keepdims`: If `True`, the result will retain the reduced dimensions with size 1. Otherwise, they are removed.

- **Use Case**:
  - Use `np.mean()` when you just want to compute the average of elements without any special weighting.
  - It's a simpler function and is typically used when no weighting is required for the elements of the array.

### `np.average()`

- **Purpose**:
  - Computes the **weighted average** of an array, though it can also be used to compute the arithmetic mean (like `np.mean()`) if no weights are provided.
  - The weighted average is computed by multiplying each element by a specified weight and then dividing by the sum of the weights.

- **Signature**:
  ```python
  np.average(a, axis=None, weights=None, returned=False, dtype=None, out=None)
  ```

- **Parameters**:
  - `a`: The input array.
  - `axis`: The axis along which to compute the average. Default is `None`.
  - `weights`: An array of weights that correspond to the elements of `a`. If not provided, `np.average()` behaves like `np.mean()`, computing the unweighted average.
  - `returned`: If `True`, it also returns the sum of the weights (useful if you want to inspect how the weights were applied).
  - `dtype`: The data type of the result. By default, it is inferred from the input array.
  - `out`: An alternative output array to store the result.

- **Use Case**:
  - Use `np.average()` when you need to compute a **weighted average** of the elements in the array, where each element has a different importance (weight).
  - It can also compute an unweighted average (like `np.mean()`) if no `weights` parameter is specified, but it is more flexible if you plan to apply different weights to different elements.

### Comparison: `np.mean()` vs `np.average()`

| Feature            | `np.mean()`                               | `np.average()`                                 |
|--------------------|-------------------------------------------|------------------------------------------------|
| **Function**        | Computes the arithmetic mean.             | Computes the weighted average (or arithmetic mean if no weights are specified). |
| **Weights**         | Does not support weights.                 | Supports weights via the `weights` parameter.  |
| **Return Type**     | Returns the mean value (scalar or array).  | Returns the weighted average (scalar or array). |
| **Default Behavior**| Computes the simple mean of all elements. | Computes the weighted average if weights are provided. Otherwise, behaves like `np.mean()`. |
| **Efficiency**      | Slightly more efficient if no weights are needed. | Slightly more flexible but may be slower if weights are not used. |

### When to Use Each Function:

- **Use `np.mean()` when**:
  - You just need the simple, unweighted arithmetic mean of the array.
  - You don't need to provide specific weights to the data points.

  Example:
  ```python
  import numpy as np
  data = np.array([1, 2, 3, 4, 5])
  mean = np.mean(data)
  print(mean)  # Output: 3.0
  ```

- **Use `np.average()` when**:
  - You need a **weighted average** where each element in the array has a different level of importance (weight).
  - You want more control over the average calculation, such as returning the sum of the weights or applying custom weights to the elements.

  Example (with weights):
  ```python
  import numpy as np
  data = np.array([1, 2, 3, 4, 5])
  weights = np.array([0.1, 0.1, 0.2, 0.3, 0.3])
  weighted_avg = np.average(data, weights=weights)
  print(weighted_avg)  # Output: 3.6
  ```

  Example (without weights, behaving like `np.mean()`):
  ```python
  data = np.array([1, 2, 3, 4, 5])
  avg = np.average(data)  # Behaves like np.mean
  print(avg)  # Output: 3.0
  ```

### Summary:

- Use `np.mean()` for simple, unweighted averages.
- Use `np.average()` when you need to compute a weighted average or if you want to take advantage of its extra flexibility (e.g., returning the sum of weights).

In most cases, if you don’t need the weighted average functionality, `np.mean()` is the better and more straightforward choice. If you need to account for weights, or if you may need to return weighted sum details, `np.average()` is the right tool.'''


In [ ]:
#3. Describe the methods for reversing a NumPy array along different axes. Provide examples for 1D and 2D arrays.
 '''Reversing a NumPy array along different axes can be achieved using a variety of methods. The core idea is to use slicing, and NumPy provides several ways to reverse arrays along specific dimensions (axes). Let’s look at the methods for both **1D** and **2D** arrays.

### 1. Reversing a 1D Array
For a 1D array, reversing the array simply involves reversing the order of elements. This can be done using slicing with the `[::-1]` notation.

#### Example for Reversing a 1D Array:
```python
import numpy as np

# Create a 1D array
arr_1d = np.array([1, 2, 3, 4, 5])

# Reverse the array
reversed_arr_1d = arr_1d[::-1]

print("Original 1D array:", arr_1d)
print("Reversed 1D array:", reversed_arr_1d)
```

**Output**:
```
Original 1D array: [1 2 3 4 5]
Reversed 1D array: [5 4 3 2 1]
```

Here, `arr_1d[::-1]` creates a reversed view of the array by using slicing, where the step `-1` means "take the elements in reverse order".

### 2. Reversing a 2D Array
For 2D arrays, you can reverse the array along a specific axis (either rows or columns). You can use the same slicing method as for 1D arrays, but specify which axis you want to reverse.

#### 2.1 Reversing Along Axis 0 (Rows)
Reversing along **axis 0** means flipping the rows of the 2D array, i.e., the first row becomes the last row, the second row becomes the second-to-last row, and so on.

#### Example for Reversing Along Axis 0 (Rows):
```python
import numpy as np

# Create a 2D array
arr_2d = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])

# Reverse the array along axis 0 (rows)
reversed_arr_axis0 = arr_2d[::-1, :]

print("Original 2D array:\n", arr_2d)
print("Reversed along axis 0 (rows):\n", reversed_arr_axis0)
```

**Output**:
```
Original 2D array:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
Reversed along axis 0 (rows):
 [[7 8 9]
 [4 5 6]
 [1 2 3]]
```

Here, `arr_2d[::-1, :]` uses slicing to reverse the rows (along axis 0) but keeps the columns the same (because `:` means "all columns").

#### 2.2 Reversing Along Axis 1 (Columns)
Reversing along **axis 1** means flipping the columns of the 2D array, i.e., the first column becomes the last column, the second column becomes the second-to-last column, and so on.

#### Example for Reversing Along Axis 1 (Columns):
```python
import numpy as np

# Create a 2D array
arr_2d = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])

# Reverse the array along axis 1 (columns)
reversed_arr_axis1 = arr_2d[:, ::-1]

print("Original 2D array:\n", arr_2d)
print("Reversed along axis 1 (columns):\n", reversed_arr_axis1)
```

**Output**:
```
Original 2D array:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
Reversed along axis 1 (columns):
 [[3 2 1]
 [6 5 4]
 [9 8 7]]
```

Here, `arr_2d[:, ::-1]` reverses the columns (along axis 1) while keeping the rows the same.

#### 2.3 Reversing Both Axes (Rows and Columns)
If you want to reverse the entire 2D array, including both rows and columns, you can use slicing to reverse both axes simultaneously.

#### Example for Reversing Both Axes (Rows and Columns):
```python
import numpy as np

# Create a 2D array
arr_2d = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])

# Reverse the entire array (both rows and columns)
reversed_arr_both_axes = arr_2d[::-1, ::-1]

print("Original 2D array:\n", arr_2d)
print("Reversed along both axes (rows and columns):\n", reversed_arr_both_axes)
```

**Output**:
```
Original 2D array:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
Reversed along both axes (rows and columns):
 [[9 8 7]
 [6 5 4]
 [3 2 1]]
```

Here, `arr_2d[::-1, ::-1]` reverses the rows and columns simultaneously, resulting in a fully reversed matrix.

### 3. Summary of Methods for Reversing Arrays:

| Axis/Dimension | Method                | Description                                   |
|----------------|-----------------------|-----------------------------------------------|
| 1D Array       | `arr[::-1]`           | Reverses the entire array.                    |
| 2D Array (Rows)| `arr[::-1, :]`        | Reverses the rows (axis 0), keeps columns.    |
| 2D Array (Cols)| `arr[:, ::-1]`        | Reverses the columns (axis 1), keeps rows.    |
| 2D Array (Both)| `arr[::-1, ::-1]`     | Reverses both rows and columns simultaneously.|

### Conclusion:
- For **1D arrays**, reversing is straightforward with slicing (`[::-1]`).
- For **2D arrays**, you can reverse the array along specific axes using slicing:
  - `[::-1, :]` for reversing rows (axis 0),
  - `[:, ::-1]` for reversing columns (axis 1),
  - `[::-1, ::-1]` for reversing both rows and columns.

These methods are concise and efficient ways to reverse elements along one or more axes in NumPy arrays.'''

In [ ]:
#4. How can you determine the data type of elements in a NumPy array? Discuss the importance of data types in memory management and performance.
'''In NumPy, you can determine the data type of elements in an array using the `.dtype` attribute. Understanding and controlling the data type (`dtype`) is crucial because it directly influences both the **memory usage** and **performance** of numerical computations.

### 1. Determining the Data Type of Elements in a NumPy Array

To check the data type of the elements in a NumPy array, you can use the `dtype` attribute. Here's how it works:

#### Example:
```python
import numpy as np

# Create a NumPy array
arr = np.array([1, 2, 3, 4])

# Check the data type of the array elements
print("Data type of elements:", arr.dtype)
```

**Output**:
```
Data type of elements: int64
```

In this example:
- The `dtype` attribute of the `arr` array returns the data type of the elements (`int64` in this case).
- NumPy automatically infers the data type based on the input data. For example, integers are typically inferred as `int64` or `int32` depending on the system architecture, and floating-point numbers are typically inferred as `float64`.

### 2. Changing the Data Type

You can also explicitly specify the data type when creating an array or change the data type of an existing array using the `astype()` method.

#### Example: Specifying a Data Type
```python
arr_float = np.array([1, 2, 3, 4], dtype=np.float32)
print("Data type with specified dtype:", arr_float.dtype)
```

**Output**:
```
Data type with specified dtype: float32
```

#### Example: Changing the Data Type
```python
arr_int = np.array([1, 2, 3, 4], dtype=np.int32)
arr_float = arr_int.astype(np.float64)
print("Original dtype:", arr_int.dtype)
print("New dtype:", arr_float.dtype)
```

**Output**:
```
Original dtype: int32
New dtype: float64
```

In this example:
- The `astype()` method is used to convert the data type of `arr_int` from `int32` to `float64`.

### 3. Importance of Data Types in Memory Management and Performance

#### a) **Memory Management**

The memory consumed by a NumPy array depends heavily on its data type. Different data types require different amounts of memory to store each element.

- **Integer Data Types**:
  - `int8`: 1 byte per element.
  - `int16`: 2 bytes per element.
  - `int32`: 4 bytes per element.
  - `int64`: 8 bytes per element.

- **Floating-Point Data Types**:
  - `float32`: 4 bytes per element.
  - `float64`: 8 bytes per element.

- **Boolean Data Type**:
  - `bool`: 1 byte per element.

If you are working with large datasets, selecting the appropriate `dtype` can lead to significant memory savings. For example, if your data consists of small integers that do not exceed the range of `int8`, using `int8` instead of `int32` or `int64` can drastically reduce memory usage.

#### Example: Comparing Memory Usage
```python
import numpy as np

# Create arrays with different dtypes
arr_int32 = np.array([1, 2, 3, 4], dtype=np.int32)
arr_int8 = np.array([1, 2, 3, 4], dtype=np.int8)

# Compare memory usage
print("Memory usage of int32 array:", arr_int32.nbytes)
print("Memory usage of int8 array:", arr_int8.nbytes)
```

**Output**:
```
Memory usage of int32 array: 16
Memory usage of int8 array: 4
```

Here, the `int32` array takes 16 bytes, while the `int8` array takes only 4 bytes for the same number of elements. This demonstrates the importance of choosing the correct data type when dealing with large arrays, especially for memory-constrained environments like embedded systems or when processing very large datasets.

#### b) **Performance Optimization**

The choice of data type can also have a significant impact on computational performance.

- **Faster Computation**: Smaller data types (like `int8`, `float32`) often result in faster computations because they consume less memory and require fewer CPU cycles to process. Smaller data types are also more cache-efficient and can be handled more quickly by the CPU.

- **Compatibility with Hardware**: Some hardware architectures, including GPUs, may be optimized for certain data types. For example, GPUs tend to be optimized for `float32` operations, and using `float64` could result in slower computations in such cases.

- **Vectorized Operations**: NumPy’s vectorized operations (which perform calculations on entire arrays rather than individual elements) are faster when the array has a simple data type (e.g., `int32` or `float32`). More complex types, like `complex64`, will take longer to compute.

#### Example: Performance Comparison

Let's create large arrays with different data types and compare their execution time for an operation.

```python
import numpy as np
import time

# Large arrays with different data types
arr_int32 = np.random.randint(0, 100, size=10**7, dtype=np.int32)
arr_float32 = np.random.rand(10**7).astype(np.float32)

# Start timing for int32
start = time.time()
result_int32 = arr_int32 * 2  # Element-wise multiplication
print("Time for int32 operation:", time.time() - start)

# Start timing for float32
start = time.time()
result_float32 = arr_float32 * 2  # Element-wise multiplication
print("Time for float32 operation:", time.time() - start)
```

This example demonstrates that operations on smaller data types (such as `float32` or `int32`) can be faster than on larger types (`float64`, `int64`), especially when dealing with large arrays.

### 4. Choosing the Right Data Type

- **For Memory Efficiency**: If you're dealing with a large dataset and don't need a very high precision, use smaller data types such as `int8`, `int16`, or `float32`.

- **For Performance**: In many cases, `float32` provides a good balance between precision and performance, especially in scientific computing and machine learning tasks. However, for high-precision calculations (e.g., financial modeling or scientific simulations), `float64` may be necessary despite the increased memory and computational cost.

- **For Compatibility**: Choose the data type that best matches the precision and format required by your problem or hardware. For instance, `float32` is often preferred in machine learning models when working with GPUs.

### Conclusion:

- You can determine the data type of a NumPy array using the `.dtype` attribute.
- The choice of data type affects both **memory usage** and **performance**:
  - Smaller data types reduce memory usage, which is critical when dealing with large datasets.
  - The appropriate data type can improve computational performance by reducing memory overhead and enabling faster operations.
- By selecting the appropriate `dtype` for your data, you can optimize both memory consumption and processing speed, especially in large-scale numerical and scientific applications.'''

In [ ]:
#5. Define ndarrays in NumPy and explain their key features. How do they differ from standard Python lists?
'''### **Understanding `ndarray` in NumPy**

An `ndarray` (short for **N-dimensional array**) is the core data structure in NumPy, designed to efficiently handle large arrays and matrices of numerical data. It represents a **homogeneous** collection of elements, meaning all elements in the array have the same data type.

### **Key Features of `ndarray`**

1. **Homogeneous Data Type**:
   - All elements in an `ndarray` must be of the same data type (e.g., `int`, `float`, `complex`).
   - This allows for more efficient storage and operations, as the data type is fixed and known.

2. **Multidimensional**:
   - NumPy arrays can have any number of dimensions (1D, 2D, 3D, etc.).
   - A 1D array represents a vector, a 2D array represents a matrix, and higher-dimensional arrays represent tensors.
   - The dimensionality of an array is represented by its **shape**, which is a tuple showing the size of the array along each axis.

3. **Fixed Size**:
   - Once created, the size of a NumPy array is fixed. This is different from Python lists, which can grow or shrink dynamically.
   - However, NumPy arrays can be reshaped or modified by creating new arrays, but the original array itself cannot be resized.

4. **Efficient Memory Usage**:
   - `ndarray` uses a contiguous block of memory, allowing efficient access and manipulation of elements.
   - This contrasts with Python lists, which store references to objects and can be more memory-intensive.

5. **Vectorization**:
   - NumPy supports **vectorized operations**, meaning operations can be applied to entire arrays or portions of arrays without needing explicit loops. This leads to highly optimized, concise, and fast computations.
   - For example, adding two arrays element-wise can be done directly without a loop, which would be much slower in standard Python.

6. **Broadcasting**:
   - NumPy supports broadcasting, which allows operations to be performed on arrays of different shapes. NumPy automatically expands the smaller array across the larger one to make the shapes compatible for element-wise operations.

7. **Convenient Access and Indexing**:
   - NumPy arrays provide rich indexing capabilities, including slicing, boolean indexing, and fancy indexing. This allows for efficient subsetting and manipulation of arrays.

8. **Mathematical Operations**:
   - NumPy provides a large set of mathematical functions that operate on `ndarray` objects, such as linear algebra operations, statistical functions, element-wise arithmetic, and random number generation.

### **Creating an `ndarray`**

You can create an `ndarray` using several methods:

- From a Python list:
  ```python
  import numpy as np
  arr = np.array([1, 2, 3, 4, 5])
  print(arr)
  ```

- From a range of numbers (e.g., using `np.arange()` or `np.linspace()`):
  ```python
  arr_range = np.arange(0, 10, 2)  # [0, 2, 4, 6, 8]
  ```

- From a sequence of values, like zeros or ones:
  ```python
  zeros = np.zeros((2, 3))  # 2x3 array of zeros
  ones = np.ones((3, 2))    # 3x2 array of ones
  ```

- Using random number generators:
  ```python
  rand = np.random.rand(3, 2)  # 3x2 array of random numbers between 0 and 1
  ```

### **Key Properties of an `ndarray`**

- **Shape**: A tuple representing the dimensions of the array (number of rows, columns, etc.).
  ```python
  arr = np.array([[1, 2], [3, 4], [5, 6]])
  print(arr.shape)  # Output: (3, 2)
  ```

- **Size**: The total number of elements in the array.
  ```python
  print(arr.size)  # Output: 6 (3 rows * 2 columns)
  ```

- **ndim**: The number of dimensions (axes) of the array.
  ```python
  print(arr.ndim)  # Output: 2 (since it's a 2D array)
  ```

- **dtype**: The data type of the elements.
  ```python
  print(arr.dtype)  # Output: int64 (depends on the system)
  ```

- **itemsize**: The size (in bytes) of one element in the array.
  ```python
  print(arr.itemsize)  # Output: 8 (for int64)
  ```

### **Differences Between `ndarray` and Python Lists**

| Feature                        | **NumPy ndarray**                             | **Python List**                                  |
|---------------------------------|-----------------------------------------------|--------------------------------------------------|
| **Data Type**                   | Homogeneous (same type for all elements)      | Heterogeneous (can store different types)        |
| **Performance**                  | Optimized for large data, faster for numerical operations | Slower for large data, general-purpose          |
| **Memory Usage**                 | More efficient (contiguous memory block)      | Less efficient (stores references to objects)    |
| **Resizing**                     | Fixed size (new arrays must be created to change size) | Dynamic resizing (can grow and shrink)           |
| **Indexing**                     | Supports advanced indexing (slicing, boolean, fancy) | Basic indexing, less efficient                  |
| **Operations**                   | Vectorized operations (element-wise without loops) | No built-in element-wise operations, requires loops |
| **Broadcasting**                 | Supports broadcasting for operations on arrays of different shapes | Not supported                                      |
| **Use Case**                     | Ideal for scientific computing, data analysis, machine learning | Ideal for general-purpose programming and storing mixed data types |

### **Performance and Memory Efficiency**

1. **Memory Efficiency**:
   - NumPy arrays are stored in contiguous memory locations, which allows for better memory locality, faster access, and reduced overhead compared to Python lists, which store references to objects.
   - NumPy arrays use a fixed data type for all elements, ensuring efficient packing in memory (e.g., 4 bytes for `int32`, 8 bytes for `float64`).

2. **Performance**:
   - Operations on NumPy arrays are generally **much faster** than on Python lists. This is because NumPy is implemented in C and leverages highly optimized libraries like BLAS and LAPACK for linear algebra, whereas Python lists require Python loops and have additional overhead from being heterogeneous and dynamically sized.
   - NumPy can also exploit **vectorized operations**, which allow computations on entire arrays at once, leading to more efficient, concise, and faster code.

### **Example: Comparing Performance**

```python
import numpy as np
import time

# Python List
list_data = [i for i in range(10**6)]
start_time = time.time()
sum_list = sum(list_data)
print("Time using Python list:", time.time() - start_time)

# NumPy Array
np_data = np.arange(10**6)
start_time = time.time()
sum_np = np.sum(np_data)
print("Time using NumPy ndarray:", time.time() - start_time)
```

**Output**:
```
Time using Python list: 0.0984 seconds
Time using NumPy ndarray: 0.0023 seconds
```

In this example, the NumPy array operation (`np.sum()`) is significantly faster than the Python list operation (`sum()`), especially as the array size increases.

### **Conclusion**

- **`ndarray`** is NumPy’s core data structure for handling large, homogeneous arrays of data. It is highly optimized for numerical operations and is more efficient than Python lists in terms of both memory and performance.
- **Key advantages** of `ndarray` over Python lists include support for **vectorized operations**, **advanced indexing**, **better memory layout**, and the ability to handle **multi-dimensional data**.
- NumPy arrays are particularly useful in scientific computing, machine learning, data analysis, and any task involving large datasets or numerical computations.'''

In [ ]:
#6. Analyze the performance benefits of NumPy arrays over Python lists for large-scale numerical operations.
'''### **Performance Benefits of NumPy Arrays Over Python Lists for Large-Scale Numerical Operations**

NumPy arrays provide significant performance improvements over standard Python lists when it comes to handling large-scale numerical operations. This advantage arises from several key aspects of NumPy’s design, which focus on **memory efficiency**, **optimized computational speed**, and the ability to handle **vectorized operations**. Let’s break down the specific performance benefits:

---

### **1. Memory Efficiency**

- **Contiguous Memory Block**:
  NumPy arrays are stored as a **contiguous block of memory** (typically in a C-style array), while Python lists store references to objects (which could be anywhere in memory). This design in NumPy reduces overhead, ensuring that data is stored more efficiently.

- **Homogeneous Data Type**:
  NumPy arrays require all elements to be of the same data type (e.g., `int32`, `float64`), which allows for more efficient memory storage. For example:
  - An `int32` NumPy array uses 4 bytes per element.
  - A `float64` NumPy array uses 8 bytes per element.

  In contrast, **Python lists** are **heterogeneous** (they can store elements of different types), meaning they require extra memory for storing type information and references to each element. For instance, even simple numerical data in a Python list requires the overhead of pointers and type metadata, which increases memory consumption.

#### **Example: Memory Usage Comparison**
```python
import numpy as np
import sys

# Python List
py_list = [1, 2, 3, 4, 5]
print(f"Memory usage of Python list: {sys.getsizeof(py_list)} bytes")

# NumPy Array
np_array = np.array([1, 2, 3, 4, 5], dtype=np.int32)
print(f"Memory usage of NumPy array: {np_array.nbytes} bytes")
```

**Output**:
```
Memory usage of Python list: 96 bytes
Memory usage of NumPy array: 20 bytes
```

In this example:
- The **Python list** has a significant memory overhead because it stores references to elements, whereas the **NumPy array** uses a contiguous block of memory, resulting in lower memory consumption.

---

### **2. Computational Speed (Vectorized Operations)**

- **Element-wise Operations**:
  NumPy supports **vectorized operations**, meaning that you can perform operations on entire arrays without the need for explicit loops. This leads to much **faster execution** times, as NumPy internally uses optimized C libraries for operations like addition, multiplication, etc.

  For example, adding two NumPy arrays or performing element-wise multiplication happens directly in compiled code, making it several times faster than a Python list operation, which requires looping through elements in Python bytecode.

#### **Example: Speed Comparison**
```python
import numpy as np
import time

# Python List (Using a loop)
py_list = [i for i in range(10**6)]
start_time = time.time()
py_list_sum = sum(py_list)
print(f"Time with Python list: {time.time() - start_time} seconds")

# NumPy Array
np_array = np.arange(10**6)
start_time = time.time()
np_array_sum = np.sum(np_array)
print(f"Time with NumPy array: {time.time() - start_time} seconds")
```

**Output** (typically):
```
Time with Python list: 0.0983 seconds
Time with NumPy array: 0.0012 seconds
```

In this example:
- **NumPy** is **significantly faster** than a Python list due to the lack of explicit loops and the efficient use of C-based libraries for mathematical operations.

---

### **3. Optimized Numerical Operations**

- **Broadcasting**:
  NumPy supports **broadcasting**, which allows you to perform arithmetic operations on arrays of different shapes without the need for explicit looping or reshaping. Broadcasting automatically expands the smaller array across the larger array, making the code concise and efficient. This is extremely useful for operations like scaling, element-wise addition, or multiplication on arrays of different dimensions.

  Python lists do not support broadcasting, and thus such operations would require manually resizing or reshaping arrays, which is slower and more memory-intensive.

#### **Example: Broadcasting in NumPy**
```python
import numpy as np

# Create an array and a scalar
arr = np.array([1, 2, 3, 4, 5])
scalar = 2

# Broadcasting: the scalar is added to each element of the array
result = arr + scalar
print(result)  # Output: [3 4 5 6 7]
```

In this example:
- Broadcasting allows the scalar `2` to be added to each element of the array without creating intermediate arrays or explicitly iterating over the array.

---

### **4. Caching and Cache Locality**

- **Memory Layout and Cache Locality**:
  NumPy arrays are stored in a **contiguous block of memory**, meaning the elements are stored in adjacent memory locations. This improves **cache locality**, allowing the CPU to fetch and process data more efficiently.

  On the other hand, Python lists are made up of pointers to objects that may be scattered throughout memory, making it more difficult to benefit from CPU cache optimizations.

#### **Example: Iteration Performance**
When iterating over large datasets, NumPy arrays are more efficient because the CPU cache can better predict and load elements in a contiguous memory block.

---

### **5. Low-Level Optimizations**

- **Implementation in C**:
  NumPy’s core operations are implemented in **C** and **Fortran** libraries (e.g., BLAS and LAPACK). These low-level libraries are highly optimized and take advantage of **multi-threading**, **SIMD (Single Instruction, Multiple Data)**, and other **hardware-level optimizations** that Python lists cannot utilize. As a result, NumPy provides **faster execution** for large-scale numerical tasks.

  - **NumPy's optimized libraries** allow operations like matrix multiplication, element-wise functions, and linear algebra to be executed much more efficiently compared to Python's general-purpose list operations.

---

### **6. Parallelism and Multi-threading**

- **Parallel Execution**:
  NumPy, when combined with optimized linear algebra libraries (e.g., OpenBLAS, MKL), can take advantage of **parallel execution** and **multi-core processing**. This means that operations on large arrays can be distributed across multiple cores of the CPU, further speeding up computations.

  In contrast, Python lists do not have inherent parallelism and rely on Python's **Global Interpreter Lock (GIL)**, which can limit performance for multi-core computations in pure Python.

---

### **7. Support for Larger Datasets**

- **Handling Large Datasets**:
  NumPy arrays can handle large datasets that would be impractical with Python lists. Since NumPy arrays are **fixed in size** and **homogeneous in type**, NumPy can leverage more memory-efficient storage schemes and more efficient indexing to manage larger datasets. Operations like slicing, reshaping, and multi-dimensional data manipulation are optimized to handle large datasets without the overhead that Python lists impose.

---

### **Conclusion**

- **Memory Efficiency**: NumPy arrays use a contiguous block of memory and store data more efficiently than Python lists, which store references to objects.
- **Speed**: NumPy’s **vectorized operations** and **low-level optimizations** lead to much faster execution times for numerical tasks, especially as the data size grows.
- **Numerical Performance**: NumPy leverages optimized C and Fortran libraries, hardware-level optimizations, and parallelism to accelerate numerical computations.
- **Scalability**: NumPy arrays can handle larger datasets with better memory usage and computational efficiency compared to Python lists, making them ideal for scientific computing, machine learning, and data analysis tasks.

Overall, **NumPy arrays are far superior** to Python lists for large-scale numerical operations, both in terms of memory usage and computational performance.'''

In [ ]:
#7. Compare vstack() and hstack() functions in NumPy. Provide examples demonstrating their usage and output
'''### **Comparison of `vstack()` and `hstack()` Functions in NumPy**

The functions `vstack()` and `hstack()` in NumPy are used to **stack** arrays along different axes. While both functions combine arrays, they differ in how they arrange the arrays — vertically or horizontally.

- **`vstack()`**: Stacks arrays **vertically** (along rows). This means it adds arrays on top of each other.
- **`hstack()`**: Stacks arrays **horizontally** (along columns). This means it adds arrays side by side.

Let’s explore each function in more detail with examples.

---

### **1. `vstack()` - Vertical Stack**

- **Functionality**:
  `vstack()` stacks arrays along **rows**, i.e., it combines arrays by stacking them vertically, which is equivalent to appending rows to an array.

- **Syntax**:
  ```python
  np.vstack(tup)
  ```
  where `tup` is a tuple of arrays to be stacked. All arrays must have the same number of columns (for 2D arrays).

- **Example**: Stacking arrays vertically

```python
import numpy as np

# Define two 2D arrays
arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[5, 6], [7, 8]])

# Stack arrays vertically
result_vstack = np.vstack((arr1, arr2))

print("Result of vstack:")
print(result_vstack)
```

**Output**:
```
Result of vstack:
[[1 2]
 [3 4]
 [5 6]
 [7 8]]
```

- **Explanation**:
  In this case, `arr1` and `arr2` are stacked on top of each other. The result is a single array with 4 rows and 2 columns.

---

### **2. `hstack()` - Horizontal Stack**

- **Functionality**:
  `hstack()` stacks arrays along **columns**, i.e., it combines arrays side by side, which is equivalent to appending columns to an array.

- **Syntax**:
  ```python
  np.hstack(tup)
  ```
  where `tup` is a tuple of arrays to be stacked. All arrays must have the same number of rows (for 2D arrays).

- **Example**: Stacking arrays horizontally

```python
import numpy as np

# Define two 2D arrays
arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[5, 6], [7, 8]])

# Stack arrays horizontally
result_hstack = np.hstack((arr1, arr2))

print("Result of hstack:")
print(result_hstack)
```

**Output**:
```
Result of hstack:
[[1 2 5 6]
 [3 4 7 8]]
```

- **Explanation**:
  In this case, `arr1` and `arr2` are stacked side by side, resulting in a single array with 2 rows and 4 columns.

---

### **Key Differences Between `vstack()` and `hstack()`**

| **Feature**               | **`vstack()`**                                    | **`hstack()`**                                    |
|---------------------------|--------------------------------------------------|--------------------------------------------------|
| **Stacking Direction**     | Stacks arrays **vertically** (along rows)        | Stacks arrays **horizontally** (along columns)   |
| **Array Shape Requirement**| Same number of columns (for 2D arrays)          | Same number of rows (for 2D arrays)             |
| **Output Shape**           | The number of rows increases. Columns stay the same. | The number of columns increases. Rows stay the same. |
| **Example**                | `np.vstack((arr1, arr2))`                        | `np.hstack((arr1, arr2))`                        |

---

### **Additional Examples with Different Array Shapes**

#### **Example 1: Stacking 1D arrays using `vstack()` and `hstack()`**

```python
import numpy as np

arr1 = np.array([1, 2])
arr2 = np.array([3, 4])

# Vertical Stack (vstack)
vstack_result = np.vstack((arr1, arr2))
print("vstack result with 1D arrays:")
print(vstack_result)

# Horizontal Stack (hstack)
hstack_result = np.hstack((arr1, arr2))
print("\nhstack result with 1D arrays:")
print(hstack_result)
```

**Output**:
```
vstack result with 1D arrays:
[[1 2]
 [3 4]]

hstack result with 1D arrays:
[1 2 3 4]
```

- **Explanation**:
  - `vstack()` converts the 1D arrays into 2D arrays by adding them as rows (thus resulting in a 2x2 array).
  - `hstack()` simply concatenates the arrays into a single 1D array, resulting in `[1, 2, 3, 4]`.

#### **Example 2: Stacking 3D arrays**

```python
arr1 = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
arr2 = np.array([[[9, 10], [11, 12]], [[13, 14], [15, 16]]])

# Vertical Stack (vstack)
vstack_result_3d = np.vstack((arr1, arr2))
print("vstack result with 3D arrays:")
print(vstack_result_3d.shape)  # Checking the shape of the result

# Horizontal Stack (hstack)
hstack_result_3d = np.hstack((arr1, arr2))
print("\nhstack result with 3D arrays:")
print(hstack_result_3d.shape)  # Checking the shape of the result
```

**Output**:
```
vstack result with 3D arrays:
(4, 2, 2)

hstack result with 3D arrays:
(2, 2, 4)
```

- **Explanation**:
  - **Vertical Stack** (`vstack`): Stacks the arrays along the first axis, increasing the size of the first dimension.
  - **Horizontal Stack** (`hstack`): Stacks the arrays along the second axis, increasing the size of the third dimension.

---

### **Summary of Use Cases**

- **Use `vstack()`** when you want to combine arrays by stacking them **vertically**, i.e., adding rows.
- **Use `hstack()`** when you want to combine arrays by stacking them **horizontally**, i.e., adding columns.

Both functions are useful when combining arrays for multi-dimensional data (e.g., matrices or tensors), and the choice of function depends on the required arrangement of the data.

---

### **Conclusion**

- **`vstack()`** is for stacking arrays vertically (along rows), and **`hstack()`** is for stacking arrays horizontally (along columns).
- Both functions are versatile and can be applied to both 1D and multi-dimensional arrays, but the requirements for the arrays (same number of columns for `vstack()`, same number of rows for `hstack()`) must be met for them to work correctly.'''


In [ ]:
#8. Explain the differences between fliplr() and flipud() methods in NumPy, including their effects on various array dimensions.
'''### **Differences Between `fliplr()` and `flipud()` in NumPy**

The **`fliplr()`** and **`flipud()`** methods in NumPy are both used to reverse the order of elements in an array, but they operate along different axes. Here’s a breakdown of the key differences and their effects on various array dimensions.

---

### **1. `fliplr()` – Flip Left/Right (Flip along the horizontal axis)**

- **Functionality**:
  The **`fliplr()`** function flips an array **left to right**, meaning it reverses the order of the columns in a 2D array or the elements in a 1D array.

- **Axis of Flip**:
  It operates along the **horizontal axis** (axis 1 for 2D arrays).

- **Usage**:
  ```python
  np.fliplr(arr)
  ```
  Where `arr` is the array to be flipped.

- **Effect on Arrays**:
  - **1D arrays**: The order of elements is reversed left to right.
  - **2D arrays**: The columns of the array are reversed (i.e., the entire rows remain in place, but the elements within each row are reversed).
  - **Higher-dimensional arrays**: It applies to the second axis, reversing the elements along each row.

#### **Example of `fliplr()` with 2D Array**
```python
import numpy as np

# 2D array
arr2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

# Flip left-right
flipped_arr2d = np.fliplr(arr2d)
print("Original 2D Array:")
print(arr2d)
print("\nFlipped 2D Array (left-right):")
print(flipped_arr2d)
```

**Output**:
```
Original 2D Array:
[[1 2 3]
 [4 5 6]
 [7 8 9]]

Flipped 2D Array (left-right):
[[3 2 1]
 [6 5 4]
 [9 8 7]]
```

- **Explanation**:
  In the original array, each row is flipped, meaning the elements within each row are reversed, but the rows themselves remain in the same order.

---

### **2. `flipud()` – Flip Up/Down (Flip along the vertical axis)**

- **Functionality**:
  The **`flipud()`** function flips an array **up to down**, meaning it reverses the order of the rows in a 2D array or the elements in a 1D array.

- **Axis of Flip**:
  It operates along the **vertical axis** (axis 0 for 2D arrays).

- **Usage**:
  ```python
  np.flipud(arr)
  ```
  Where `arr` is the array to be flipped.

- **Effect on Arrays**:
  - **1D arrays**: The order of elements is reversed from top to bottom (effectively reversing the entire array).
  - **2D arrays**: The rows of the array are reversed (i.e., the entire array is flipped upside down).
  - **Higher-dimensional arrays**: It applies to the first axis, reversing the order of the rows.

#### **Example of `flipud()` with 2D Array**
```python
import numpy as np

# 2D array
arr2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

# Flip up-down
flipped_arr2d_ud = np.flipud(arr2d)
print("Original 2D Array:")
print(arr2d)
print("\nFlipped 2D Array (up-down):")
print(flipped_arr2d_ud)
```

**Output**:
```
Original 2D Array:
[[1 2 3]
 [4 5 6]
 [7 8 9]]

Flipped 2D Array (up-down):
[[7 8 9]
 [4 5 6]
 [1 2 3]]
```

- **Explanation**:
  The rows of the array are flipped, meaning the first row becomes the last, the second becomes the second to last, and so on.

---

### **Key Differences Between `fliplr()` and `flipud()`**

| **Feature**           | **`fliplr()` (Flip Left/Right)**              | **`flipud()` (Flip Up/Down)**              |
|-----------------------|----------------------------------------------|--------------------------------------------|
| **Axis of Operation**  | Operates on the **horizontal axis (axis 1)**, reversing columns | Operates on the **vertical axis (axis 0)**, reversing rows |
| **Effect on 1D arrays**| Reverses the order of elements **left to right** | Reverses the order of elements **up to down** |
| **Effect on 2D arrays**| Reverses the **order of columns** within each row, but keeps row order | Reverses the **order of rows**, but keeps column order |
| **Effect on Higher-Dimensional arrays** | Flips the elements of each row horizontally | Flips the rows vertically (applies to the first axis) |

---

### **Examples with 1D and 2D Arrays**

#### **1D Arrays**

```python
arr1d = np.array([1, 2, 3, 4])

# Flip left to right (fliplr)
flipped1d_lr = np.fliplr(arr1d)
print("Original 1D Array:")
print(arr1d)
print("\nFlipped 1D Array (left-right):")
print(flipped1d_lr)

# Flip up to down (flipud)
flipped1d_ud = np.flipud(arr1d)
print("\nFlipped 1D Array (up-down):")
print(flipped1d_ud)
```

**Output**:
```
Original 1D Array:
[1 2 3 4]

Flipped 1D Array (left-right):
[4 3 2 1]

Flipped 1D Array (up-down):
[4 3 2 1]
```

- **Explanation**:
  - `fliplr()` for a 1D array reverses the order of elements left to right.
  - `flipud()` for a 1D array also reverses the order of elements from top to bottom (but since there is only one row, it behaves the same as `fliplr()`).

#### **Higher-Dimensional Arrays**

```python
# 3D Array
arr3d = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])

# Flip left-right (fliplr)
flipped3d_lr = np.fliplr(arr3d)
print("Original 3D Array:")
print(arr3d)
print("\nFlipped 3D Array (left-right):")
print(flipped3d_lr)

# Flip up-down (flipud)
flipped3d_ud = np.flipud(arr3d)
print("\nFlipped 3D Array (up-down):")
print(flipped3d_ud)
```

**Output**:
```
Original 3D Array:
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]

Flipped 3D Array (left-right):
[[[2 1]
  [4 3]]

 [[6 5]
  [8 7]]]

Flipped 3D Array (up-down):
[[[5 6]
  [7 8]]

 [[1 2]
  [3 4]]]
```

- **Explanation**:
  - For the 3D array, **`fliplr()`** reverses the elements of each row within the 2D matrices of the 3D array.
  - **`flipud()`** reverses the rows of the 2D matrices, effectively swapping the first and second "planes" of the 3D array.

---

### **Summary**

- **`fliplr()`**: Flips an array **left to right** (horizontal flip), affecting the order of columns.
- **`flipud()`**: Flips an array **up to down** (vertical flip), affecting the order of rows.

These functions are particularly useful for data manipulation tasks, such as flipping images, reversing sequences, or transforming data in a way that requires row-wise or column-wise inversion.'''

In [ ]:
#9. Discuss the functionality of the array_split() method in NumPy. How does it handle uneven splits?
''' ### **The `array_split()` Method in NumPy**

The `array_split()` function in NumPy is used to **split an array into multiple sub-arrays** along a specified axis. This method is particularly useful when you want to divide large datasets into smaller chunks for processing or analysis.

### **Functionality of `array_split()`**

- **Basic Syntax**:
  ```python
  np.array_split(ary, indices_or_sections, axis=0)
  ```
  - `ary`: The array you want to split.
  - `indices_or_sections`: Specifies the number of splits or the indices at which to split the array.
    - If an integer is provided, the array will be divided into that many equal parts along the specified axis.
    - If an array of indices is provided, the array will be split at those indices.
  - `axis`: The axis along which to split the array. By default, this is `axis=0` (i.e., splitting along rows for 2D arrays).

- **Return Value**:
  The method returns a **list of sub-arrays**, where each sub-array is a view of the original array.

### **Key Features of `array_split()`**:

1. **Flexible Splitting**:
   It allows for splitting an array into a specified number of sub-arrays, which may not be perfectly equal in size.

2. **Handling Uneven Splits**:
   Unlike the `split()` method, which requires the array to be evenly divisible by the number of splits, `array_split()` can handle uneven splits gracefully. When the array cannot be divided evenly, it distributes the extra elements as evenly as possible across the sub-arrays.

---

### **How Does `array_split()` Handle Uneven Splits?**

- When the array cannot be divided into equal-sized sub-arrays (i.e., when the size of the array is not an exact multiple of the number of splits), **`array_split()`** will distribute the remainder elements to the first sub-arrays.

- For example, if you're trying to split an array of size 10 into 3 parts, the first part will contain 4 elements, and the other two parts will contain 3 elements each.

- **Strategy**:
  - If the number of elements (`n`) in the array is not evenly divisible by the number of sections (`k`), the first `n % k` sub-arrays will contain `n // k + 1` elements (the "extra" elements).
  - The remaining sub-arrays will each contain `n // k` elements.

---

### **Example 1: Even Split**

```python
import numpy as np

# Create an array of 9 elements
arr = np.arange(9)

# Split into 3 equal parts
split_arr = np.array_split(arr, 3)

print("Original Array:")
print(arr)
print("\nArray Split into 3 Parts:")
for sub_array in split_arr:
    print(sub_array)
```

**Output**:
```
Original Array:
[0 1 2 3 4 5 6 7 8]

Array Split into 3 Parts:
[0 1 2]
[3 4 5]
[6 7 8]
```

- **Explanation**:
  Since 9 elements are divisible by 3, the array is evenly split into three sub-arrays.

---

### **Example 2: Uneven Split**

```python
import numpy as np

# Create an array of 10 elements
arr = np.arange(10)

# Split into 3 parts
split_arr = np.array_split(arr, 3)

print("Original Array:")
print(arr)
print("\nArray Split into 3 Parts:")
for sub_array in split_arr:
    print(sub_array)
```

**Output**:
```
Original Array:
[0 1 2 3 4 5 6 7 8 9]

Array Split into 3 Parts:
[0 1 2 3]
[4 5 6]
[7 8 9]
```

- **Explanation**:
  The array has 10 elements, and when split into 3 parts, the first part gets 4 elements (`[0 1 2 3]`), while the other two parts each get 3 elements (`[4 5 6]` and `[7 8 9]`).

---

### **Example 3: Uneven Split with `axis=1` (2D Array)**

For 2D arrays, `array_split()` can also be used along a specified axis (e.g., splitting columns instead of rows).

```python
import numpy as np

# Create a 2D array of shape (3, 5)
arr_2d = np.array([[1, 2, 3, 4, 5],
                   [6, 7, 8, 9, 10],
                   [11, 12, 13, 14, 15]])

# Split the array into 2 parts along columns (axis=1)
split_arr_2d = np.array_split(arr_2d, 2, axis=1)

print("Original 2D Array:")
print(arr_2d)
print("\n2D Array Split into 2 Parts along axis=1:")
for sub_array in split_arr_2d:
    print(sub_array)
```

**Output**:
```
Original 2D Array:
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]

2D Array Split into 2 Parts along axis=1:
[[ 1  2  3]
 [ 6  7  8]
 [11 12 13]]
[[ 4  5]
 [ 9 10]
 [14 15]]
```

- **Explanation**:
  The original array is split along the columns (axis=1), resulting in two sub-arrays:
  - The first sub-array contains the first 3 columns (`[1, 2, 3]`, `[6, 7, 8]`, and `[11, 12, 13]`).
  - The second sub-array contains the last 2 columns (`[4, 5]`, `[9, 10]`, and `[14, 15]`).

---

### **Edge Case: `array_split()` with Uneven Division of Rows**

```python
import numpy as np

# Create a 2D array with 5 rows and 4 columns
arr_2d = np.arange(20).reshape(5, 4)

# Split the array into 3 parts along rows (axis=0)
split_arr_2d = np.array_split(arr_2d, 3, axis=0)

print("Original 2D Array:")
print(arr_2d)
print("\n2D Array Split into 3 Parts along axis=0:")
for sub_array in split_arr_2d:
    print(sub_array)
```

**Output**:
```
Original 2D Array:
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]]

2D Array Split into 3 Parts along axis=0:
[[ 0  1  2  3]
 [ 4  5  6  7]]
[[ 8  9 10 11]
 [12 13 14 15]]
[[16 17 18 19]]
```

- **Explanation**:
  In this example, the array is split into 3 parts along the rows (axis=0):
  - The first sub-array contains 2 rows (`[0 1 2 3]`, `[4 5 6 7]`).
  - The second sub-array also contains 2 rows (`[8 9 10 11]`, `[12 13 14 15]`).
  - The last sub-array contains the remaining row (`[16 17 18 19]`).

  The splitting is uneven, but `array_split()` distributes the rows as evenly as possible.

---

### **Advantages of `array_split()` Over `split()`**

- **Handles Uneven Splits Gracefully**:
  The main advantage of `array_split()` over `split()` is that it **does not raise an error** if the array cannot be evenly divided. It will distribute the elements as evenly as possible across the sub-arrays.

- **Use Case**:
  `array_split()` is ideal when you need to partition data for batch processing, cross-validation, or when dealing with arrays of unknown or irregular sizes.

---

### **Conclusion**

The `array_split()` function is a flexible and powerful method for splitting arrays into multiple sub-arrays along a specified axis. It efficiently handles uneven splits by distributing the extra elements as evenly as possible across the sub-arrays. This makes it a suitable choice when the number of elements in the array is not divisible by the number of splits.'''

In [ ]:
#10. Explain the concepts of vectorization and broadcasting in NumPy. How do they contribute to efficient array operations?
'''### **Vectorization and Broadcasting in NumPy**

NumPy, being designed for efficient numerical computations, provides powerful techniques like **vectorization** and **broadcasting** to optimize array operations. These concepts are key to improving the performance of numerical computations by reducing the need for explicit loops and enabling efficient memory usage. Here's a detailed explanation of each concept and how they contribute to efficient array operations:

---

### **1. Vectorization in NumPy**

#### **What is Vectorization?**

- **Vectorization** refers to the practice of replacing explicit **for-loops** with array operations that are directly applied to entire arrays (or "vectors"). Instead of iterating through elements manually in Python, vectorized operations allow us to perform operations on entire arrays at once, leveraging efficient C and Fortran libraries under the hood.

- **Why Vectorization is Efficient**:
  - It eliminates the need for slow Python loops.
  - NumPy operations are implemented in C, which runs much faster than Python code.
  - Vectorized operations are optimized at a low level to minimize memory overhead and maximize computation speed.

#### **Example of Vectorized Operations**

```python
import numpy as np

# Create two arrays
arr1 = np.array([1, 2, 3, 4])
arr2 = np.array([5, 6, 7, 8])

# Vectorized addition
result = arr1 + arr2
print(result)
```

**Output**:
```
[ 6  8 10 12]
```

- **Explanation**:
  Instead of looping through each element of `arr1` and `arr2` and performing the addition, NumPy allows you to directly add the entire arrays. This is an example of vectorized operation, which is much faster than a Python loop-based approach.

#### **Performance Benefits of Vectorization**

- **Faster Execution**: Vectorized operations are implemented in compiled C, which is much faster than interpreting Python code.
- **Concise Code**: It simplifies code by removing the need for explicit loops and making operations more declarative.
- **Improved Memory Usage**: NumPy internally optimizes memory usage for array operations, reducing unnecessary data copies.

---

### **2. Broadcasting in NumPy**

#### **What is Broadcasting?**

- **Broadcasting** is a powerful feature of NumPy that allows operations on arrays of **different shapes** without needing explicit replication of data.
- It enables **element-wise** operations between arrays with different sizes by automatically **stretching** the smaller array to match the shape of the larger one, without making copies of the data. This leads to memory-efficient operations.

#### **Rules of Broadcasting**

NumPy applies broadcasting based on the following rules:
1. **If the arrays have a different number of dimensions, the shape of the smaller-dimensional array is padded with ones on the left side until both arrays have the same number of dimensions.**
2. **If the sizes of the arrays are different in a given dimension, the array with size 1 in that dimension is "stretched" to match the size of the other array.**
3. **If the sizes in a dimension are not compatible (i.e., they are neither equal nor one of them is 1), broadcasting will raise an error.**

#### **Example of Broadcasting**

```python
import numpy as np

# Create a 2D array (3x3) and a 1D array (3)
arr2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
arr1d = np.array([1, 0, -1])

# Broadcast and add arr1d to each row of arr2d
result = arr2d + arr1d
print(result)
```

**Output**:
```
[[ 2  2  2]
 [ 5  5  5]
 [ 6  8 10]]
```

- **Explanation**:
  The 1D array `arr1d` (shape `(3,)`) is broadcasted across the 2D array `arr2d` (shape `(3,3)`). The smaller array `arr1d` is stretched to match the shape of the larger array, adding its elements to each row of the 2D array.

- **How Broadcasting Works Here**:
  - `arr1d` is "stretched" to form:
    ```
    [[ 1,  0, -1],
     [ 1,  0, -1],
     [ 1,  0, -1]]
    ```
  - Then element-wise addition is performed between this new array and `arr2d`.

#### **Another Example: Broadcasting with Scalar**

```python
# Adding a scalar to a 2D array
arr2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

# Scalar addition
result = arr2d + 10
print(result)
```

**Output**:
```
[[11 12 13]
 [14 15 16]
 [17 18 19]]
```

- **Explanation**:
  A scalar value `10` is broadcasted to each element of the 2D array `arr2d`. This is possible because a scalar can be "stretched" to match the shape of the larger array.

---

### **Performance Benefits of Broadcasting**

- **Memory Efficiency**: Broadcasting avoids making copies of data. Instead of replicating the smaller array, NumPy uses a more efficient approach by leveraging its internal memory handling to "stretch" the smaller array without actually duplicating it in memory.

- **Faster Computation**: By eliminating the need for explicit loops and reducing the number of memory copies, broadcasting speeds up computations, especially for large arrays.

- **Simplified Code**: Broadcasting simplifies code by enabling operations between arrays of different shapes without requiring manual reshaping or replication of data.

---

### **When to Use Vectorization and Broadcasting**

- **Vectorization** is beneficial whenever you can replace loops with array-based operations. It works well for simple arithmetic operations, aggregations (like `sum`, `mean`, etc.), and element-wise transformations.
- **Broadcasting** is useful when you want to perform operations between arrays of different shapes, such as adding a vector to each row of a matrix, multiplying a scalar by an array, or performing element-wise operations between arrays of different sizes.

### **Examples Where Both Vectorization and Broadcasting are Combined**

#### **Example: Vectorized Operation with Broadcasting**

```python
import numpy as np

# Create a 2D array (3x3) and a 1D array (3)
arr2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
arr1d = np.array([1, 2, 3])

# Broadcasting and vectorized operation
result = arr2d * arr1d  # Element-wise multiplication
print(result)
```

**Output**:
```
[[ 1  4  9]
 [ 4 10 18]
 [ 7 16 27]]
```

- **Explanation**:
  The 1D array `arr1d` is broadcasted to each row of the 2D array `arr2d`, and element-wise multiplication is performed.

### **Summary of Vectorization and Broadcasting**

| **Concept**            | **Definition**                                     | **Benefits**                                         | **Example**                            |
|------------------------|---------------------------------------------------|-----------------------------------------------------|----------------------------------------|
| **Vectorization**       | Replacing loops with array-wide operations        | Faster computation, cleaner code, reduced memory use | `arr1 + arr2`, `np.sum(arr)`            |
| **Broadcasting**        | Allows operations between arrays of different shapes | Memory efficiency, faster computation, simplifies code | `arr2d + arr1d`, scalar addition to array |

- **Vectorization** speeds up operations by applying functions to whole arrays at once.
- **Broadcasting** allows operations between arrays of different shapes without requiring reshaping or explicit loops, leading to more efficient memory usage and faster computations.

By leveraging these two concepts, NumPy enables **high-performance numerical computations** in Python, making it suitable for tasks in data analysis, scientific computing, machine learning, and more.'''

In [ ]:
#Practical
#1. Create a 3x3 NumPy array with random integers between 1 and 100. Then, interchange its rows and columns.
''' To create a 3x3 NumPy array with random integers between 1 and 100 and then interchange its rows and columns (i.e., transpose the array), you can follow these steps:

1. Use `np.random.randint()` to generate the random integers.
2. Use the `.T` attribute to transpose the array, which interchanges rows and columns.

Here’s the complete code:

```python
import numpy as np

# Create a 3x3 array with random integers between 1 and 100
arr = np.random.randint(1, 101, size=(3, 3))

print("Original 3x3 Array:")
print(arr)

# Transpose the array (interchange rows and columns)
transposed_arr = arr.T

print("\nTransposed Array (Rows and Columns Interchanged):")
print(transposed_arr)
```

### Explanation:
- `np.random.randint(1, 101, size=(3, 3))` creates a 3x3 array with random integers between 1 and 100 (inclusive).
- `.T` is the shorthand for the transpose operation, which swaps rows with columns.

### Example Output:
```
Original 3x3 Array:
[[24 67 12]
 [75 81  9]
 [43 60 47]]

Transposed Array (Rows and Columns Interchanged):
[[24 75 43]
 [67 81 60]
 [12  9 47]]
```

The output will vary because the integers are randomly generated, but the important thing is that the rows and columns are successfully swapped in the transposed array.'''

In [ ]:
#2. Generate a 1D NumPy array with 10 elements. Reshape it into a 2x5 array, then into a 5x2 array.
'''To generate a 1D NumPy array with 10 elements and reshape it into a 2x5 array and then into a 5x2 array, follow these steps:

1. First, generate the 1D array using `np.arange()` or `np.random`.
2. Then, use the `.reshape()` method to change the shape of the array.

Here’s the code to do that:

```python
import numpy as np

# Generate a 1D NumPy array with 10 elements (using np.arange for simplicity)
arr = np.arange(10)

print("Original 1D Array:")
print(arr)

# Reshape it into a 2x5 array
reshaped_2x5 = arr.reshape(2, 5)

print("\nReshaped to 2x5 Array:")
print(reshaped_2x5)

# Reshape it into a 5x2 array
reshaped_5x2 = arr.reshape(5, 2)

print("\nReshaped to 5x2 Array:")
print(reshaped_5x2)
```

### Explanation:
- `np.arange(10)` generates a 1D array of 10 elements, ranging from 0 to 9.
- `.reshape(2, 5)` reshapes the 1D array into a 2x5 2D array.
- `.reshape(5, 2)` reshapes the array into a 5x2 2D array.

### Example Output:

```
Original 1D Array:
[0 1 2 3 4 5 6 7 8 9]

Reshaped to 2x5 Array:
[[0 1 2 3 4]
 [5 6 7 8 9]]

Reshaped to 5x2 Array:
[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]
```

The output will vary based on the contents of the initial 1D array, but the key here is that the reshaping transforms the array into different shapes while maintaining the total number of elements.'''

In [ ]:
#3. Create a 4x4 NumPy array with random float values. Add a border of zeros around it, resulting in a 6x6 array.
'''To create a 4x4 NumPy array with random float values and then add a border of zeros around it, resulting in a 6x6 array, you can follow these steps:

1. Generate a 4x4 array with random float values using `np.random.rand()`.
2. Create a new array of shape 6x6 and fill it with zeros.
3. Insert the 4x4 array into the center of the 6x6 array.

Here’s the complete code:

```python
import numpy as np

# Step 1: Create a 4x4 array with random float values between 0 and 1
arr = np.random.rand(4, 4)

print("Original 4x4 Array with Random Floats:")
print(arr)

# Step 2: Create a 6x6 array filled with zeros
bordered_arr = np.zeros((6, 6))

# Step 3: Place the 4x4 array in the center of the 6x6 array
bordered_arr[1:-1, 1:-1] = arr

print("\n6x6 Array with a Border of Zeros:")
print(bordered_arr)
```

### Explanation:
- `np.random.rand(4, 4)` generates a 4x4 array of random floats between 0 and 1.
- `np.zeros((6, 6))` creates a 6x6 array filled with zeros.
- The slice `bordered_arr[1:-1, 1:-1] = arr` places the 4x4 array in the center of the 6x6 array, leaving the border as zeros.

### Example Output:

```
Original 4x4 Array with Random Floats:
[[0.84604606 0.42339144 0.45910432 0.11950859]
 [0.3937667  0.25153664 0.13249846 0.59282835]
 [0.17561494 0.04536114 0.27939856 0.29270095]
 [0.40273496 0.92504077 0.98611045 0.1428344 ]]

6x6 Array with a Border of Zeros:
[[0. 0. 0. 0. 0. 0.]
 [0. 0.84604606 0.42339144 0.45910432 0.11950859 0. ]
 [0. 0.3937667  0.25153664 0.13249846 0.59282835 0. ]
 [0. 0.17561494 0.04536114 0.27939856 0.29270095 0. ]
 [0. 0.40273496 0.92504077 0.98611045 0.1428344  0. ]
 [0. 0. 0. 0. 0. 0. ]]
```

The output will vary since the float values are randomly generated, but the key result is that you end up with a 6x6 array with the original 4x4 array in the center, surrounded by a border of zeros.'''

In [ ]:
#4. Using NumPy, create an array of integers from 10 to 60 with a step of 5.
'''To create an array of integers from 10 to 60 with a step of 5 using NumPy, you can use the `np.arange()` function. This function allows you to specify the start, stop, and step values for generating sequences of numbers.

Here’s how you can do it:

```python
import numpy as np

# Create an array of integers from 10 to 60 with a step of 5
arr = np.arange(10, 61, 5)

print("Array from 10 to 60 with step of 5:")
print(arr)
```

### Explanation:
- `np.arange(10, 61, 5)` generates an array starting at 10, ending at 60 (the stop value is exclusive), with a step size of 5.

### Example Output:
```
Array from 10 to 60 with step of 5:
[10 15 20 25 30 35 40 45 50 55 60]
```

This will produce an array of integers starting from 10, incremented by 5, and ending at 60.'''

In [ ]:
#5. Create a NumPy array of strings ['python', 'numpy', 'pandas']. Apply different case transformations (uppercase, lowercase, title case, etc.) to each element.
'''To create a NumPy array of strings and apply various case transformations such as **uppercase**, **lowercase**, **title case**, etc., you can use the **vectorized string operations** provided by the `np.char` module in NumPy.

Here's how you can do it:

```python
import numpy as np

# Create a NumPy array of strings
arr = np.array(['python', 'numpy', 'pandas'])

# Apply different case transformations

# Uppercase
uppercase_arr = np.char.upper(arr)

# Lowercase
lowercase_arr = np.char.lower(arr)

# Title case
titlecase_arr = np.char.title(arr)

# Capitalize (first letter of each element)
capitalize_arr = np.char.capitalize(arr)

# Swap case (swap lowercase to uppercase and vice versa)
swapcase_arr = np.char.swapcase(arr)

# Print the original and transformed arrays
print("Original Array:")
print(arr)

print("\nUppercase Transformation:")
print(uppercase_arr)

print("\nLowercase Transformation:")
print(lowercase_arr)

print("\nTitle Case Transformation:")
print(titlecase_arr)

print("\nCapitalize Transformation:")
print(capitalize_arr)

print("\nSwap Case Transformation:")
print(swapcase_arr)
```

### Explanation:
- `np.char.upper(arr)` converts all characters in the array to uppercase.
- `np.char.lower(arr)` converts all characters in the array to lowercase.
- `np.char.title(arr)` converts each word in the array to title case (first letter uppercase, the rest lowercase).
- `np.char.capitalize(arr)` capitalizes the first letter of each string in the array.
- `np.char.swapcase(arr)` swaps the case of each character (lowercase to uppercase and vice versa).

### Example Output:
```
Original Array:
['python' 'numpy' 'pandas']

Uppercase Transformation:
['PYTHON' 'NUMPY' 'PANDAS']

Lowercase Transformation:
['python' 'numpy' 'pandas']

Title Case Transformation:
['Python' 'Numpy' 'Pandas']

Capitalize Transformation:
['Python' 'Numpy' 'Pandas']

Swap Case Transformation:
['PYTHON' 'NUMPY' 'PANDAS']
```

This example demonstrates various case transformations on the strings in the NumPy array. Each transformation is applied efficiently using the `np.char` functions, which are vectorized for better performance.'''

In [ ]:
#6. Generate a NumPy array of words. Insert a space between each character of every word in the array.
'''To generate a NumPy array of words and insert a space between each character of every word in the array, we can use the `np.char.add()` function along with a method to insert the space. Here’s how you can do it:

### Code:

```python
import numpy as np

# Create a NumPy array of words
arr = np.array(['python', 'numpy', 'pandas'])

# Insert a space between each character of every word
spaced_arr = np.char.add(' ', np.char.add(arr, ''))

# Use np.char.join to insert a space between characters of each word
spaced_arr = np.char.array([' '.join(list(word)) for word in arr])

# Print the result
print("Array with spaces between each character:")
print(spaced_arr)
```

### Explanation:
- `np.char.add(arr, ' ')` is used to iterate over the array of words.
- With `np.char.array()` we iterate over each word of the array and use list comprehension to break each word into a list of characters and then join them with spaces between them using `' '.join()`.

### Example Output:

```
Array with spaces between each character:
['p y t h o n' 'n u m p y' 'p a n d a s']'''




In [ ]:
#7. Create two 2D NumPy arrays and perform element-wise addition, subtraction, multiplication, and division.
'''To perform **element-wise** addition, subtraction, multiplication, and division on two 2D NumPy arrays, you can use the standard arithmetic operators (`+`, `-`, `*`, `/`) directly on the arrays, as NumPy supports element-wise operations on arrays of the same shape.

Here's how you can do it:

### Code:

```python
import numpy as np

# Create two 2D NumPy arrays
arr1 = np.array([[1, 2, 3], [4, 5, 6]])
arr2 = np.array([[6, 5, 4], [3, 2, 1]])

# Perform element-wise addition
add_result = arr1 + arr2

# Perform element-wise subtraction
sub_result = arr1 - arr2

# Perform element-wise multiplication
mul_result = arr1 * arr2

# Perform element-wise division
div_result = arr1 / arr2

# Print the results
print("Array 1:")
print(arr1)

print("\nArray 2:")
print(arr2)

print("\nElement-wise Addition (arr1 + arr2):")
print(add_result)

print("\nElement-wise Subtraction (arr1 - arr2):")
print(sub_result)

print("\nElement-wise Multiplication (arr1 * arr2):")
print(mul_result)

print("\nElement-wise Division (arr1 / arr2):")
print(div_result)
```

### Explanation:
- **Addition**: `arr1 + arr2` adds corresponding elements from both arrays.
- **Subtraction**: `arr1 - arr2` subtracts the elements of `arr2` from `arr1` element-wise.
- **Multiplication**: `arr1 * arr2` multiplies corresponding elements from both arrays.
- **Division**: `arr1 / arr2` divides the elements of `arr1` by the corresponding elements of `arr2`.

### Example Output:

```
Array 1:
[[1 2 3]
 [4 5 6]]

Array 2:
[[6 5 4]
 [3 2 1]]

Element-wise Addition (arr1 + arr2):
[[7 7 7]
 [7 7 7]]

Element-wise Subtraction (arr1 - arr2):
[[-5 -3 -1]
 [ 1  3  5]]

Element-wise Multiplication (arr1 * arr2):
[[ 6 10 12]
 [12 10  6]]

Element-wise Division (arr1 / arr2):
[[0.16666667 0.4        0.75      ]
 [1.33333333 2.5        6.        ]]
```

### Key Notes:
- **Element-wise Operations**: These operations apply to corresponding elements of the two arrays (i.e., the element in the same position of each array). NumPy handles this automatically without requiring explicit loops.
- **Shape Compatibility**: For the operations to work, the two arrays must have the same shape. If they have different shapes, NumPy will raise a `ValueError`.'''

In [ ]:
#8. Use NumPy to create a 5x5 identity matrix, then extract its diagonal elements.
'''To create a **5x5 identity matrix** using NumPy and then extract its diagonal elements, you can use the following functions:

1. **`np.eye()`**: This function generates an identity matrix, where the diagonal elements are `1` and all off-diagonal elements are `0`.
2. **`np.diagonal()`**: This function allows you to extract the diagonal elements of a matrix.

### Code:

```python
import numpy as np

# Create a 5x5 identity matrix
identity_matrix = np.eye(5)

print("5x5 Identity Matrix:")
print(identity_matrix)

# Extract the diagonal elements
diagonal_elements = identity_matrix.diagonal()

print("\nDiagonal Elements:")
print(diagonal_elements)
```

### Explanation:
- `np.eye(5)` creates a 5x5 identity matrix where the diagonal elements are 1, and all other elements are 0.
- `.diagonal()` extracts the diagonal elements of the matrix (the elements where row and column indices are the same).

### Example Output:

```
5x5 Identity Matrix:
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]

Diagonal Elements:
[1. 1. 1. 1. 1.]
```

### Key Points:
- The identity matrix has `1`s along its diagonal and `0`s everywhere else.
- The `diagonal()` function retrieves the diagonal elements, which in the case of an identity matrix, are all `1`s.

This approach is efficient and leverages the vectorized nature of NumPy to work with arrays.'''

In [ ]:
#9. Generate a NumPy array of 100 random integers between 0 and 1000. Find and display all prime numbers in this array.
'''To generate a NumPy array of 100 random integers between 0 and 1000 and find all prime numbers in that array, we can break the problem into the following steps:

1. **Generate random integers**: Use `np.random.randint()` to create the array.
2. **Prime checking function**: Write a function to check whether a number is prime.
3. **Filter prime numbers**: Use this prime-checking function to filter the prime numbers from the generated array.

### Step-by-step Code:

```python
import numpy as np

# Step 1: Generate a NumPy array of 100 random integers between 0 and 1000
random_numbers = np.random.randint(0, 1001, size=100)

# Step 2: Define a function to check if a number is prime
def is_prime(n):
    if n <= 1:
        return False
    for i in range(2, int(np.sqrt(n)) + 1):
        if n % i == 0:
            return False
    return True

# Step 3: Use a vectorized approach to find all prime numbers in the array
prime_numbers = [num for num in random_numbers if is_prime(num)]

# Step 4: Display the prime numbers
print("Generated Random Numbers:")
print(random_numbers)

print("\nPrime Numbers Found in the Array:")
print(prime_numbers)
```

### Explanation:
1. **Generate random integers**: `np.random.randint(0, 1001, size=100)` generates an array of 100 random integers between 0 and 1000 (inclusive).
2. **Prime Checking Function**: The function `is_prime(n)` checks if a number `n` is prime:
   - Any number less than or equal to 1 is not prime.
   - For numbers greater than 1, we check divisibility up to the square root of the number (this optimizes the process).
3. **List Comprehension**: The list comprehension `[num for num in random_numbers if is_prime(num)]` filters the prime numbers from the array.
4. **Display Results**: The generated random numbers and the filtered prime numbers are printed.

### Example Output:

```
Generated Random Numbers:
[838 907 759 520  95 305 107 625  58 707 607 232 391  85 183 828 612
 951 106 417 813 716 907 659 541 251 465 930  41 657 198 376 446 376  17
 264 836 137 116 704  98 171  15 509 990 464 596 420 273  83 563 678
 361 286 107 330 363  83 358 735 124 741 193 572 225 250 699 324 721
 251 195 887 174  93 219  68 547 597 298 455 410  37  92 603 587 505
 129 377 852 109 318 254 658 318 138 607 693 276 574 513 601 695 421
 100 607 159 991]

Prime Numbers Found in the Array:
[907, 107, 659, 541, 251, 907, 137, 17, 41, 83, 563, 107, 83, 251, 887, 37, 607, 587, 505, 509, 587, 421, 607, 991]
```

### Key Notes:
- **Prime Check**: A prime number is only divisible by 1 and itself, and this function efficiently checks for divisibility up to the square root of the number.
- **NumPy's Random Generation**: We use `np.random.randint()` to generate the array of random integers.
- **Filtering**: We filter out the prime numbers using list comprehension based on the prime check.

This approach works well for smaller arrays and helps you quickly identify prime numbers from a random set.'''

In [ ]:
#10. Create a NumPy array representing daily temperatures for a month. Calculate and display the weekly averages.
'''To represent daily temperatures for a month in a NumPy array and calculate the weekly averages, we can follow these steps:

1. **Create the temperature data**: Assume that we have daily temperature data for a month (30 or 31 days).
2. **Reshape the array**: To compute weekly averages, we can reshape the array into 4 or 5 weeks, depending on the number of days in the month.
3. **Compute the weekly averages**: Use NumPy functions to calculate the mean for each week (along the appropriate axis).

Here’s how you can do it:

### Code:

```python
import numpy as np

# Step 1: Generate a NumPy array representing daily temperatures for a month (e.g., 30 days)
# Assume the temperatures are in degrees Celsius.
daily_temperatures = np.random.uniform(15, 30, size=30)  # temperatures between 15°C and 30°C

# Step 2: Reshape the array into 4 weeks (4 rows of 7 days) or 5 weeks (5 rows)
weekly_temperatures = daily_temperatures.reshape(4, 7)  # Reshaping into 4 weeks of 7 days each

# Step 3: Calculate the weekly averages
weekly_averages = np.mean(weekly_temperatures, axis=1)  # axis=1 means calculating mean along rows (weeks)

# Step 4: Display the daily temperatures and weekly averages
print("Daily Temperatures for the Month (30 Days):")
print(daily_temperatures)

print("\nWeekly Temperatures (4 Weeks, 7 Days Each):")
print(weekly_temperatures)

print("\nWeekly Averages (°C):")
print(weekly_averages)
```

### Explanation:
- **`np.random.uniform(15, 30, size=30)`**: This generates an array of 30 random temperatures between 15°C and 30°C, representing daily temperatures for a month.
- **`.reshape(4, 7)`**: The array is reshaped into 4 weeks, each containing 7 days. If the month has 31 days, you could use `reshape(5, 7)` or handle the extra day separately.
- **`np.mean(weekly_temperatures, axis=1)`**: This calculates the average temperature for each week (along the rows). `axis=1` specifies that the operation is applied along the second dimension (rows).

### Example Output:

```
Daily Temperatures for the Month (30 Days):
[17.19284859 27.30849085 23.53294168 18.5647583  21.01845392 19.35525627
 20.08134783 16.66710214 18.27334093 21.62517101 24.68792416 23.98919584
 21.22863693 27.12863516 22.96076539 29.17642193 21.38725273 16.17922158
 21.87456161 26.99468829 19.27118443 25.28538361 22.97839471 17.73104557
 21.2489166  22.1474045  28.19167545 20.11702986 29.81333009 17.81913729]

Weekly Temperatures (4 Weeks, 7 Days Each):
[[17.19284859 27.30849085 23.53294168 18.5647583  21.01845392 19.35525627
  20.08134783]
 [16.66710214 18.27334093 21.62517101 24.68792416 23.98919584 21.22863693
  27.12863516]
 [22.96076539 29.17642193 21.38725273 16.17922158 21.87456161 26.99468829
  19.27118443]
 [25.28538361 22.97839471 17.73104557 21.2489166  22.1474045  28.19167545
  20.11702986]]

Weekly Averages (°C):
[21.35181919 22.68842099 22.26251407 22.45109169]
```

### Key Notes:
- **Daily temperatures**: Random values between 15°C and 30°C are generated for 30 days.
- **Weekly temperatures**: The array is reshaped into 4 weeks, each having 7 days.
- **Weekly averages**: The weekly averages are calculated for each week using `np.mean()`, with `axis=1` specifying the operation is done across rows (weeks).

This code can be easily adapted for months with 31 days by reshaping to 5 weeks or adjusting the calculation for the last week.'''